<?php
/*
CREATE TABLE IPR_IMPORTED_PROSPECT (
		IPR_ID					INT NOT NULL AUTO_INCREMENT,
		IPR_IPB_ID				INT(11) NULL,
		IPR_COMPANY_NAME		VARCHAR(255) NULL,
		IPR_COMPANY_NUMBER		VARCHAR(255) NULL,
		IPR_ADDRESS1			VARCHAR(255) NULL,
		IPR_ADDRESS2			VARCHAR(255) NULL,
		IPR_TOWN_NAME			VARCHAR(255) NULL,
		IPR_RAW_ACTIVITIES		VARCHAR(255) NULL,
		IPR_MAPPED_ACTIVITIES	VARCHAR(255) NULL,
		IPR_POSTCODE			VARCHAR(255) NULL,
		IPR_PHONE				VARCHAR(255) NULL,
		IPR_PHON2				VARCHAR(255) NULL,
		IPR_EMAIL				VARCHAR(255) NULL,
		IPR_EMAIL2				VARCHAR(255) NULL,
		IPR_CONTACT_TITLE		VARCHAR(255) NULL,
		IPR_CONTACT_FIRSTNAME	VARCHAR(255) NULL,
		IPR_CONTACT_LASTNAME	VARCHAR(255) NULL,
		IPR_CONTACT_FUNCTION	VARCHAR(255) NULL,
		IPR_DESCRIPTION			VARCHAR(255) NULL,
		IPR_STATUS				VARCHAR(255) NULL,

		IPR_DUPL_COMPANY_NAME	VARCHAR(100) NULL,
		IPR_DUPL_EMAIL			VARCHAR(100) NULL,
		IPR_DUPL_PHONE			VARCHAR(100) NULL,
		IPR_DUPL_COMPANY_NUMBER	VARCHAR(100) NULL,
		IPR_DUPL_POSTCODE		VARCHAR(100) NULL,
		PRIMARY KEY (`IPR_ID`)
);
 */
class baseIPR_IMPORTED_PROSPECT extends QDOrm{
	public $table	='test.IPR_IMPORTED_PROSPECT';

	public $pk		='IPR_ID';

	public $fields = array(
		'IPR_ID'					,
		'IPR_IPB_ID'				,
		'IPR_COMPANY_NAME'			,
		'IPR_COMPANY_NUMBER'		,
		'IPR_ADDRESS1'				,
		'IPR_ADDRESS2'				,
		'IPR_TOWN_NAME'				,
		'IPR_RAW_ACTIVITIES'		,
		'IPR_MAPPED_ACTIVITIES'		,
		'IPR_POSTCODE'				,
		'IPR_PHONE'					,
		'IPR_PHONE2'				,
		'IPR_EMAIL'					,
		'IPR_EMAIL2'				,
		'IPR_CONTACT_TITLE'			,
		'IPR_CONTACT_FIRSTNAME'		,
		'IPR_CONTACT_LASTNAM	E'	,
		'IPR_CONTACT_FUNCTIO	N'	,
		'IPR_DESCRIPTION'			,
		'IPR_STATUS'				,
		'IPR_DUPL_COMPANY_NAME'		,
		'IPR_DUPL_EMAIL'			,
		'IPR_DUPL_PHONE'			,
		'IPR_DUPL_COMPANY_NUMBER'	,
		'IPR_DUPL_POSTCODE'
	);

	public function getConnectionName(){
		return 'main';
	}
}

class IPR_IMPORTED_PROSPECT extends baseIPR_IMPORTED_PROSPECT{

}
